
VIEW=less
PY=python

.PHONY : run clean

run : interpreterext2.py programext2.py
	$(PY) interpreterext2.py

viewI : interpreterext2.py
	$(VIEW) interpreterext2.py

viewP : programext2.py
	$(VIEW) programext2.py
   
clean :
	-\rm *.pyc
